// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using arcane_synergy_app_backend.Data;

#nullable disable

namespace arcane_synergy_app_backend.Migrations
{
    [DbContext(typeof(ArcaneSynergyContext))]
    [Migration("20251210152319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("arcane_synergy_app_backend.Models.Admission", b =>
                {
                    b.Property<int>("AdmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdmissionId"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CountOfTransfers")
                        .HasColumnType("int");

                    b.Property<string>("DX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateNotified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayOfWeekAdmitted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DischargeTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinalDischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MonthAdmitted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextAdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientEngagement")
                        .HasColumnType("int");

                    b.Property<string>("PatientID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ReadmissionFlag")
                        .HasColumnType("bit");

                    b.Property<string>("SeenBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TCMDueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeOfAdmission")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalADMVisits")
                        .HasColumnType("int");

                    b.Property<int>("TotalERVisits")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdmissionId");

                    b.HasIndex("PatientID");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("arcane_synergy_app_backend.Models.Patient", b =>
                {
                    b.Property<string>("PatientID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Clinic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insurance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MRN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Version")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("arcane_synergy_app_backend.Models.Transfer", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferId"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AdmissionId")
                        .HasColumnType("int");

                    b.Property<string>("DX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateNotified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DischargeTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFinalDischarge")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TimeOfAdmission")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransferId");

                    b.HasIndex("AdmissionId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("arcane_synergy_app_backend.Models.Admission", b =>
                {
                    b.HasOne("arcane_synergy_app_backend.Models.Patient", "Patient")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientID");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("arcane_synergy_app_backend.Models.Transfer", b =>
                {
                    b.HasOne("arcane_synergy_app_backend.Models.Admission", "Admission")
                        .WithMany("Transfers")
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");
                });

            modelBuilder.Entity("arcane_synergy_app_backend.Models.Admission", b =>
                {
                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("arcane_synergy_app_backend.Models.Patient", b =>
                {
                    b.Navigation("Admissions");
                });
#pragma warning restore 612, 618
        }
    }
}
